apiVersion: apps/v1
kind: Deployment
metadata:
    name: poc-deploy
    labels:
      env: dev
spec:
    selector:
      matchLabels:
        app: web-app
    replicas: 3
    template:
      metadata:
        name: web-app
        labels:
          app: web-app
      spec:
        containers:
          - name: web-app
            image: paulmur/paul-poc:latest